services:
  api:
    build: .
    container_name: projetocarol_api
    ports:
      - "5001:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=ProjetoCarolDb;User=root;Password=Senhaforte123!;
    volumes:
      - uploads_data:/app/uploads

  mysql:
    image: mysql:8.0
    container_name: projetocarol_mysql
    ports:
      - "3307:3306"        # Porta MySQL mapeada para o host
    environment:
      MYSQL_ROOT_PASSWORD: root        # Senha do root
      MYSQL_DATABASE: ProjetoCarolDb        # Banco inicial
      # MYSQL_USER e MYSQL_PASSWORD removidos
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  uploads_data:
