version: '3.9'

services:
  api:
    build: .
    container_name: projetocarol_api
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProjetoCarolDb;User Id=sa;Password=G7m!R9x@Q2v#L8t$Z4pK;Encrypt=True;TrustServerCertificate=True;
    volumes:
      - uploads_data:/app/uploads

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: projetocarol_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=G7m!R9x@Q2v#L8t$Z4pK
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
  uploads_data: