services:
  api:
    build: .
    container_name: projetocarol_api
    ports:
      - "5001:8080"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=ProjetoCarolDb;User=root;Password=JyaC64MA5_3yRr0e!;
    volumes:
      - uploads_data:/app/uploads

  mysql:
    image: mysql:8.0
    container_name: projetocarol_mysql
    ports:
      - "3307:3306"        
    environment:
      MYSQL_ROOT_PASSWORD: JyaC64MA5_3yRr0e!       
      MYSQL_DATABASE: ProjetoCarolDb        
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  uploads_data:
